projects:
  paddelapp:
    schemaPath: src/graphql/schema.json
    includes:
      - 'y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
