projects:
  paddelapp:
    schemaPath: amplify/backend/api/paddelapp/build/schema.graphql
    includes:
      - 'y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
